spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PWD}
    url: jdbc:mariadb://localhost:3306/cadmus
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
