spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}/cadmus
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    locations: db/migration/mariadb
